// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyB83cFIm8LxMuPtHIHGY9jZl4YvAs1UX18',
    appId: '1:914352196749:web:e85203ae04179e31f866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    authDomain: 'renting-wala-27d06.firebaseapp.com',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
    measurementId: 'G-6LM56R8KKQ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCQduY28OYEnsvlmPVEakcufVeH8KBDBOQ',
    appId: '1:914352196749:android:ee37314f98f2d15af866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDP32imn2GeQfLqyUsgECsiAJ5VIbx4GTc',
    appId: '1:914352196749:ios:80005cab290e9d10f866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
    iosClientId: '914352196749-o5j8vlo39knclg8ob6g3j6qh8nda5iaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.borezy',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDP32imn2GeQfLqyUsgECsiAJ5VIbx4GTc',
    appId: '1:914352196749:ios:80005cab290e9d10f866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
    iosClientId: '914352196749-o5j8vlo39knclg8ob6g3j6qh8nda5iaq.apps.googleusercontent.com',
    iosBundleId: 'com.example.borezy',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCqCv60gcTJN9oBiBfkP-GwxELENgPQk1c',
    appId: '1:914352196749:web:b318006e2d4f7aadf866c4',
    messagingSenderId: '914352196749',
    projectId: 'renting-wala-27d06',
    authDomain: 'renting-wala-27d06.firebaseapp.com',
    databaseURL: 'https://renting-wala-27d06-default-rtdb.firebaseio.com',
    storageBucket: 'renting-wala-27d06.appspot.com',
    measurementId: 'G-D30FBEGBYW',
  );
}
